services:
  postgres:
    image: postgres
    container_name: postgres-LinkLens
    restart: always
    env_file:
      - ./bot/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - linklens_network

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    env_file:
      - ./parser/.env
    ports:
      - "8000:8000"
    networks:
      - linklens_network

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - '8001:8000'
    env_file:
      - ./bot/.env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - parser
    networks:
      - linklens_network

volumes:
  postgres_data:


networks:
  linklens_network:
    driver: bridge
