services:
  postgres:
    image: postgres
    container_name: postgres-LinkLens
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  # bot:
  #   build: .
  #   ports:
  #     - '8000:8000'
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - postgres

    
volumes:
  postgres_data: